alter table content_item drop foreign key FK_gudw6viy7lrf5t5hetw7mbgh5;
alter table content_item drop foreign key FK_pyrd1nhijag5ct0ee9xqq4h78;
alter table content_item drop foreign key FK_9kpe6whsov3ur9rph4ih2vi5a;
alter table diff_task drop foreign key FK_dlrthwe594xvfeta3kyuih3ip;
alter table diff_task_attrs drop foreign key FK_1sbjtesix8hkq310i84lfg0xi;
alter table diff_task_attrs drop foreign key FK_72rsx022j2wu9noi6jldvq95r;
alter table export_task drop foreign key FK_g6atpiywpo2100kn6ovix7uet;
alter table hl7psu_task drop foreign key FK_pev4urgkk7id2h1ijhv8domjx;
alter table ian_task drop foreign key FK_1fuh251le2hid2byw90hd1mly;
alter table instance drop foreign key FK_jxfu47kwjk3kkkyrwewjw8a4n;
alter table instance drop foreign key FK_7w6f9bi2w91qr2abl6ddxnrwq;
alter table instance drop foreign key FK_6pnwsvi69g5ypye6gjo26vn7e;
alter table instance drop foreign key FK_s4tgrew4sh4qxoupmk3gihtrk;
alter table location drop foreign key FK_hjtlcwsvwihs4khh961d423e7;
alter table location drop foreign key FK_bfk5vl6eoxaf0hhwiu3rbgmkn;
alter table mpps drop foreign key FK_o49fec996jvdo31o7ysmsn9s2;
alter table mpps drop foreign key FK_nrigpgue611m33rao03nnfe5l;
alter table mpps drop foreign key FK_grl2idmms10qq4lhmh909jxtj;
alter table mpps drop foreign key FK_ofg0lvfxad6r5oigw3y6da27u;
alter table mwl_item drop foreign key FK_6qj8tkh6ib9w2pjqwvqe23ko;
alter table mwl_item drop foreign key FK_ot32lpvialton54xqh636c4it;
alter table mwl_item drop foreign key FK_vkxtls2wr17wgxnxj7b2fe32;
alter table mwl_item drop foreign key FK_44qwwvs50lgpog2cqmicxgt1f;
alter table patient drop foreign key FK_5lgndn3gn7iug3kuewiy9q124;
alter table patient drop foreign key FK_sk77bwjgaoetvy1pbcgqf08g;
alter table patient drop foreign key FK_39gahcxyursxfxe2ucextr65s;
alter table patient drop foreign key FK_rj42ffdtimnrcwmqqlvj24gi2;
alter table patient drop foreign key FK_56r2g5ggptqgcvb3hl11adke2;
alter table patient_id drop foreign key FK_oo232lt89k1b5h8mberi9v152;
alter table rel_study_pcode drop foreign key FK_fryhnb2ppb6fcop3jrrfwvnfy;
alter table rel_study_pcode drop foreign key FK_mnahh8fh77d365m6w2x4x3f4q;
alter table retrieve_task drop foreign key FK_mxokt1gw5g1e7rc3ssotvuqix;
alter table series drop foreign key FK_bdj2kuutidekc2en6dckev7l6;
alter table series drop foreign key FK_oiq81nulcmtg6p85iu31igtf5;
alter table series drop foreign key FK_pu4p7k1o9hleuk9rmxvw2ybj6;
alter table series drop foreign key FK_5n4bxxb2xa7bvvq26ao7wihky;
alter table series drop foreign key FK_1og1krtgxfh207rtqjg0r7pbd;
alter table series_query_attrs drop foreign key FK_eiwosf6pcc97n6y282cv1n54k;
alter table series_req drop foreign key FK_se4n39as61wwf92ggbfc9yglo;
alter table series_req drop foreign key FK_bcn0jtvurqutw865pwp34pejb;
alter table series_req drop foreign key FK_bdkjk6ww0ulrb0nhf41c7liwt;
alter table soundex_code drop foreign key FK_dh7lahwi99hk6bttrk75x4ckc;
alter table sps_station_aet drop foreign key FK_js5xqyw5qa9rpttwmck14duow;
alter table study drop foreign key FK_5w0oynbw061mwu1rr9mrb6kj4;
alter table study drop foreign key FK_lp0rdx659kewq8qrqg702yfyv;
alter table study drop foreign key FK_e3fdaqhw7u60trs5aspf4sna9;
alter table study drop foreign key FK_49eet5qgcsb32ktsqrf1mj3x2;
alter table study_query_attrs drop foreign key FK_sxccj81423w8o6w2tsb7nshy9;
alter table verify_observer drop foreign key FK_105wt9hglqsmtnoxgma9x18vj;
alter table verify_observer drop foreign key FK_qjgrn9rfyyt6sv14utk9ijcfq;
drop table if exists code;
drop table if exists content_item;
drop table if exists dicomattrs;
drop table if exists diff_task;
drop table if exists diff_task_attrs;
drop table if exists export_task;
drop table if exists hl7psu_task;
drop table if exists ian_task;
drop table if exists id_sequence;
drop table if exists instance;
drop table if exists issuer;
drop table if exists location;
drop table if exists metadata;
drop table if exists mpps;
drop table if exists mwl_item;
drop table if exists patient;
drop table if exists patient_id;
drop table if exists person_name;
drop table if exists queue_msg;
drop table if exists rel_study_pcode;
drop table if exists retrieve_task;
drop table if exists series;
drop table if exists series_query_attrs;
drop table if exists series_req;
drop table if exists soundex_code;
drop table if exists sps_station_aet;
drop table if exists stgcmt_result;
drop table if exists study;
drop table if exists study_query_attrs;
drop table if exists uidmap;
drop table if exists verify_observer;
