# build and test image on its own

version: '2'

services:
    mysqldb:
        image: yishunxin/mysql-dcm4chee:5.7
        container_name: db_node_one
        environment:
            MYSQL_ROOT_PASSWORD: nb2018
            MYSQL_DATABASE: pacsdb
            MYSQL_USER: pacs
            MYSQL_PASSWORD: pacs
        ports:
            - "3306:3306"